const HARD_WORDS = [
  {clue:"Process plants use to make food", answer:"PHOTOSYNTHESIS"},
  {clue:"Study of living organisms", answer:"BIOLOGY"},
  {clue:"Five-sided polygon", answer:"PENTAGON"},
  {clue:"Change shape during life cycle", answer:"METAMORPHOSIS"},
  {clue:"Organism's interacting community", answer:"ECOSYSTEM"},
  {clue:"State of equilibrium", answer:"HOMEOSTASIS"},
  {clue:"Science of classification", answer:"TAXONOMY"},
  {clue:"Force resisting motion", answer:"FRICTION"},
  {clue:"Measure of disorder", answer:"ENTROPY"},
  {clue:"Study of Earth's atmosphere", answer:"METEOROLOGY"},
  {clue:"Related to bones", answer:"OSTEOLOGY"},
  {clue:"Study of the mind", answer:"PSYCHOLOGY"},
  {clue:"Branch of mathematics for rates", answer:"CALCULUS"},
  {clue:"Study of human past", answer:"ARCHAEOLOGY"},
  {clue:"Large mammal with trunk", answer:"ELEPHANT"},
  {clue:"Highest point on Earth", answer:"MOUNTAINEERING"},
  {clue:"Compound of sugar & alcohol", answer:"FERMENTATION"},
  {clue:"A short dramatic play", answer:"VIGNETTE"},
  {clue:"Not easily explained", answer:"ENIGMATIC"},
  {clue:"Not keeping still", answer:"KINETIC"},
  {clue:"Opposite of convex", answer:"CONCAVE"},
  {clue:"Study of weather", answer:"CLIMATOLOGY"},
  {clue:"Remarkably great", answer:"EXTRAORDINARY"},
  {clue:"Relating to hearing", answer:"AUDITORY"},
  {clue:"Mixing of races", answer:"HYBRIDIZATION"},
  {clue:"State of being numerous", answer:"PLETHORA"},
  {clue:"Quick and energetic", answer:"VIGOROUS"},
  {clue:"Multiple countries working together", answer:"INTERNATIONAL"},
  {clue:"Not able to be changed", answer:"IRREVOCABLE"},
  {clue:"Fear of confined spaces", answer:"CLAUSTROPHOBIA"},
  {clue:"Study of structure", answer:"ANATOMY"},
  {clue:"One who loves books", answer:"BIBLIOPHILE"},
  {clue:"Condition of having two forms", answer:"DIMORPHISM"},
  {clue:"Relating to stars", answer:"ASTRONOMICAL"},
  {clue:"Period of record keeping", answer:"CHRONOLOGY"},
  {clue:"A scholar or learned person", answer:"ERUDITE"},
  {clue:"A long, adventurous voyage", answer:"ODYSSEY"},
  {clue:"Clear and persuasive", answer:"COHERENT"},
  {clue:"Impossible to enter", answer:"IMPENETRABLE"},
  {clue:"One who studies fossils", answer:"PALEONTOLOGIST"},
  {clue:"Person who loves fine food", answer:"GOURMET"},
  {clue:"Related to the sun", answer:"SOLAR"},
  {clue:"Study of motion forces", answer:"DYNAMICS"},
  {clue:"A hidden meaning", answer:"ALLEGORY"},
  {clue:"Relating to sound waves", answer:"ACOUSTIC"},
  {clue:"One who avoids work", answer:"IDLER"},
  {clue:"To reduce in intensity", answer:"ABATE"},
  {clue:"Abundant, overflowing", answer:"RIFE"},
  {clue:"Lacking harmony", answer:"DISSONANT"},
  {clue:"Capable of being shaped", answer:"MALLEABLE"},
  {clue:"Belief without proof", answer:"SUPPOSITION"},
  {clue:"Careful and precise", answer:"METICULOUS"},
  {clue:"A long-standing tradition", answer:"ANACHRONISM"},
  {clue:"Belonging to an earlier time", answer:"ARCHEAN"},
  {clue:"Skilled at persuading", answer:"ELOQUENT"},
  {clue:"Skipping from subject to subject", answer:"RAMBLING"},
  {clue:"Something hard to bear", answer:"ONEROUS"},
  {clue:"A sign of future events", answer:"OMEN"},
  {clue:"Permanent, unchanging", answer:"CONSTANT"},
  {clue:"Extremely small", answer:"MINUSCULE"},
  {clue:"Group of related people", answer:"CLAN"},
  {clue:"A secret plan", answer:"CONSPIRACY"},
  {clue:"Strong dislike or hatred", answer:"ANIMOSITY"},
  {clue:"The art of effective speaking", answer:"RHETORIC"},
  {clue:"Skill in public speaking", answer:"ORATORY"},
  {clue:"Short saying with advice", answer:"ADAGE"},
  {clue:"Use of many words", answer:"VERBIAGE"},
  {clue:"Food for thought", answer:"PROVOCATIVE"},
  {clue:"Extremely complicated", answer:"BYZANTINE"},
  {clue:"The way something is done", answer:"METHODOLOGY"},
  {clue:"Brief and to the point", answer:"CONCISE"},
  {clue:"Study of animal behavior", answer:"ETHOLOGY"},
  {clue:"Able to be believed", answer:"PLAUSIBLE"},
  {clue:"Not easily satisfied", answer:"INSATIABLE"},
  {clue:"Relating to painting", answer:"PICTORIAL"},
  {clue:"An official order", answer:"MANDATE"},
  {clue:"A confusing situation", answer:"QUANDARY"},
  {clue:"Skillful, clever", answer:"ADEPT"},
  {clue:"Relating to time", answer:"TEMPORAL"},
  {clue:"Hidden or secret", answer:"COVERT"},
  {clue:"A person who writes poems", answer:"POETESS"},
  {clue:"Extreme patriotism", answer:"JINGOISM"},
  {clue:"Act of showing mercy", answer:"PARDON"},
  {clue:"A natural ability", answer:"KNACK"},
  {clue:"Unclear, vague", answer:"AMBIGUOUS"},
  {clue:"Not typical; unusual", answer:"ECCENTRIC"},
  {clue:"Relating to the mind", answer:"COGNITIVE"},
  {clue:"Not able to be harmed", answer:"INVULNERABLE"},
  {clue:"Extremely noisy", answer:"CLAMOROUS"},
  {clue:"To settle a disagreement", answer:"ARBITRATE"},
  {clue:"Serious or gloomy", answer:"SOMBRE"},
  {clue:"An ornamental band", answer:"FASCIA"},
  {clue:"A strong desire", answer:"YEARNING"},
  {clue:"Unchanging over time", answer:"STABLE"},
  {clue:"To puzzle or confuse", answer:"PERPLEX"}
];
